name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and push to DockerHub
      run:      
        VERSION=$(date +%s)
        docker login --username edgarcardozo --password ${{ secrets.DOCKERHUB_TOKEN }}
        docker build . --file Dockerfile --tag registry.hub.docker.com/edgarcardozo/ia-knn:${VERSION}
        docker push registry.hub.docker.com/edgarcardozo/ia-knn:${VERSION}
